apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep01susi
  labels:
    app: phppr
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phppr
    spec:
      containers:
        - name: php
          image: susigugh/phppr:v1
  selector:
    matchLabels:
      app: phppr
