apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep01susi
  labels:
    app: mysqldb
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: susigugh/mysql01:v1
  selector:
    matchLabels:
      app: mysqldb
