apiVersion: v1
kind: Service
metadata:
  labels:
    app: phppr
  name: php-srv
spec:
  ports:
  - nodePort: 30880
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: phppr
  type: NodePort

