name: Mirror Sync

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  mirror-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Perform mirror sync
        uses: ActionsDesk/mirror-sync@main
        with:
          remote-repository-url: https://susigugh01+1-at-016589193088:XcNhCrkDe+dPndDYWURRJUCzMOxOdi0SBoOHpuSbOsc=@https://git-codecommit.ap-south-1.amazonaws.com/v1/repos/susigugh
